#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.native.cacheKind=none

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# Forces JetBrains Compose to map matching components onto Intel architectures
org.jetbrains.compose.experimental.apple.element=true